require 'pry'
require 'open-uri'
require 'nokogiri'

require_relative '../lib/crypto_prices/version.rb'
require_relative '../lib/crypto_prices/coin.rb'
require_relative '../lib/crypto_prices/cli.rb'
require_relative '../lib/crypto_prices/scraper.rb'
require_relative '../lib/crypto_prices/menu.rb'
require_relative '../lib/crypto_prices/logo.rb'
